/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
